### ISSUE TITLE
Is there a working demo?

### ISSUE THREAD

**Issue by iraStricker** [yuanqing/menu-aim#6]
Hi,
I really would like to test your Javascript version of jQuery menu aim. :) 
Is there a working example somewhere? 
The CodePen demo don't seem to work anymore? (https://codepen.io/lyuanqing/pen/paLgwN)

**Comment by yuanqing** [comment]
Just had a quick look at this. The demo should work now!

**Comment by iraStricker** [comment]
Thank you!

**Comment by baidoct** [comment]
The demo ain't working again..
